/**
 * English gallery chrome copy, constrained by `GalleryStrings` to the shape of the Chinese
 * dictionary in strings.ts: the surfaces and the library topics are named here, as there.
 */
import type { GalleryStrings } from "./strings";

export const en: GalleryStrings = {
  brand: {
    title: "Penguin UI",
  },
  site: {
    home: "Home",
    surfaces: "Surfaces",
    foundations: "Foundations",
    fonts: "Fonts",
    pages: "Pages",
    search: "Search surfaces",
    searchShortcut: "Ctrl K",
    noMatches: "No surface matches.",
    nav: "Surfaces",
    onThisPage: "On this page",
    settings: "View settings",
    menu: "Open the menu",
    closeMenu: "Close the menu",
    notFound: (id) => `There is no page named “${id}”.`,
    allSurfaces: "All surfaces",
    feedbackTitle: "Feedback",
    feedbackBody:
      "Quote the breadcrumb at the end of a frame's toolbar, or copy the page's address with the link button.",
    feedbackExample: "Frost › Chat · dark",
  },
  surfaceGroups: {
    conversation: "Conversation",
    workbench: "Workbench",
    resources: "Resources",
    measure: "Measure",
    system: "System",
  },
  surfaces: {
    chat: {
      title: "Chat",
      description:
        "A finished Task: thinking, three tool calls, a diff, and a Markdown answer with a table and code.",
      how: "Sidebar › any row of the session list.",
    },
    "chat-running": {
      title: "Chat · tool running",
      description:
        "A Task mid-run: a command is executing, and the tool row shows the running state and its timer.",
      how: "Sidebar › a session row with the running mark.",
    },
    "chat-thinking": {
      title: "Chat · thinking",
      description:
        "A Task mid-run: the model is thinking; the thinking row shows the running state and the text keeps growing.",
      how: "Sidebar › a session row with the running mark.",
    },
    "chat-streaming": {
      title: "Chat · streaming",
      description:
        "A Task mid-run: the answer is streaming in and reveals the way the current theme does it; once done it holds for a moment and streams again, on a loop.",
      how: "Sidebar › a session row with the running mark.",
    },
    "chat-approval": {
      title: "Chat · awaiting approval",
      description:
        "A Task waiting on a human: a command needs approval; allow or deny it and the Task carries on and ends.",
      how: "Sidebar › a session row with the approval mark.",
    },
    "chat-new": {
      title: "New chat",
      description:
        "The draft page: pick the Agent, Workspace, approval mode and model, then type and send the first message.",
      how: "Sidebar › New chat.",
    },
    agents: {
      title: "Agents",
      description:
        "The Agent list: each Agent's activity curve and its session, tool, Skill and schedule counts.",
      how: "Sidebar › Agents.",
    },
    "agent-settings": {
      title: "Agent settings",
      description:
        "One Agent's settings page: overview, prompt, memory, runtime, tools, Skills, hooks, Vault and schedule tabs.",
      how: "Agents › any Agent.",
    },
    schedules: {
      title: "Schedules",
      description:
        "The Agent settings' schedule tab: periods, next fire time, the bound Session and model.",
      how: "Agents › Agent settings › the Schedules tab.",
    },
    "schedules-project": {
      title: "Schedules (whole Project)",
      description:
        "Every Agent's scheduled tasks in this Project, grouped by Agent: enable, edit and delete them all here, and see the files that failed to parse.",
      how: "The avatar at the bottom left › the account menu › Schedules.",
    },
    plugins: {
      title: "Plugins",
      description:
        "The plugin library by category, with search and filters; installed Skills and hooks per Agent.",
      how: "Sidebar › Plugins.",
    },
    "plugin-detail": {
      title: "Plugin detail",
      description:
        "One plugin's page: its description, the Skills it brings, its file browser and the install action.",
      how: "Plugins › any plugin.",
    },
    models: {
      title: "Models",
      description:
        "The model table by provider: the default model, credentials, prices, context windows and usage.",
      how: "Sidebar › Models.",
    },
    machines: {
      title: "Machines",
      description:
        "This machine and remote ones: install state, connections, probe results, and adding an ssh host.",
      how: "Sidebar › Machines (admins only).",
    },
    usage: {
      title: "Cost center",
      description:
        "Thirty days of usage: Tokens, cost, requests and success rate, grouped by date, Agent, model or Session, with the error panel.",
      how: "Sidebar › Cost center.",
    },
    benchmark: {
      title: "Evaluation center",
      description:
        "The Benchmark list: published and draft status, case counts, and the score trend across evaluations.",
      how: "Sidebar › Evaluation center.",
    },
    "benchmark-detail": {
      title: "Benchmark detail",
      description:
        "One Benchmark: the score curve, each evaluation's case scores, and the cases' statement and rubric files.",
      how: "Evaluation center › any Benchmark.",
    },
    settings: {
      title: "Settings",
      description:
        "The settings dialog: profile, general, appearance (theme, mode, accent, text size, fonts), account, and the server settings.",
      how: "The account menu at the bottom of the sidebar › Settings.",
    },
    "settings-appearance": {
      title: "Appearance settings",
      description:
        "The settings dialog on its Appearance page: theme, mode, accent, the five text sizes and the font pairing — where theme switching lives.",
      how: "The account menu at the bottom of the sidebar › Settings › Appearance.",
    },
    login: {
      title: "Login",
      description:
        "The sign-in page: the login card over the decorative canvas. Any password signs the demo account in.",
      how: "Any address while signed out.",
    },
  },
  home: {
    eyebrow: "Surface gallery",
    title: "Penguin UI",
    lead: "The real Web App, running in three themes, two modes, five text sizes, the font pairings and two languages — on an in-browser demo API, fully clickable.",
    app: "The app",
    appLead:
      "This is the app itself: the sidebar, every center, the chat and the settings all open. The theme and size controls drive the app in the frame; sending a message streams a scripted reply.",
    index: "Surface index",
    indexLead:
      "One page per surface: the app opened on it, under whatever theme, size and fonts you set.",
    library: "Component library",
    libraryLead:
      "The real Web components, one page per kind, rendered under the theme, mode, size and fonts you set — and interactive.",
    fonts: "Fonts",
    fontsLead: "Each theme's default faces, the current choice, specimens and licences.",
  },
  rail: {
    theme: "Theme",
    themeNames: { github: "Primer", modern: "Frost", geek: "Console" },
    mode: "Mode",
    accent: "Accent",
    accentTheme: "Theme's own",
    size: "Size",
    sizeNames: { xs: "XS", s: "S", m: "M", l: "L", xl: "XL" },
    sizeTitle: (name, px) => `${name} · ${px}px root`,
    fontLatin: "Latin font",
    fontCjk: "CJK font",
    fontTheme: "Theme default",
    fontSystem: "System",
    language: "Language",
    viewport: "Viewport",
    viewports: { desktop: "Desktop", phone: "Phone" },
    langNames: { en: "EN", zh: "中文" },
    modes: { light: "Light", dark: "Dark", system: "System" },
  },
  readout: {
    label: "Fonts in use",
    latin: "Latin",
    cjk: "CJK",
    mono: "Mono",
    system: "System",
    pending: "Reading…",
  },
  crumb: {
    modes: { light: "light", dark: "dark" },
    phone: "phone",
  },
  intro: {
    resolving: "Resolving tokens…",
  },
  frame: {
    open: "Open standalone",
    reload: "Reload",
    frameOf: (theme) => `The app in ${theme}`,
    how: "Where it is in the app",
    route: "Route",
    signedOut: "signed out",
  },
  section: {
    copyLink: "Copy link",
    copyBreadcrumb: "Copy breadcrumb",
    unset: "unset",
  },
  foundations: {
    surfaces: "Surfaces",
    inks: "Inks",
    lines: "Lines",
    inkWords: ["Text", "Muted", "Subtle"],
    accent: "Accent",
    presetsHint:
      "The theme's own accent and the five presets this theme lists; another theme's presets paint nothing here",
    themeAccent: "theme",
    sampleSend: "Send",
    selectedRow: "Selected",
    sampleLink: "Open the docs",
    linkHover: "hover",
    tones: "Tones",
    toneWords: {
      success: "Running",
      attention: "Waiting",
      danger: "Failed",
      done: "Done",
      neutral: "Idle",
      info: "Syncing",
    },
    charts: "Chart series",
    tokenSeries: "Token mix",
    code: "Code and diff",
    codeLines: {
      before: "const hits = rank(q).slice(0, ",
      removed: "3",
      added: "6",
      after: ");",
      selected: "return cite(hits);",
    },
    typeNote:
      "Each row is set in its own role's tokens; the Chinese column shows how the theme's faces set Chinese with Latin runs in it.",
    scene: {
      pageTier: "page",
      cardTitle: "Docs Expert",
      cardMeta: "3 sessions · $0.0231",
      nested: "Inner radius = outer radius − padding",
      primary: "Save",
      secondary: "Cancel",
      input: "Search sessions",
      badge: "Running",
      menuTier: "z-[60] menu",
      menuItems: ["Pin", "Rename", "Move to…"],
      backdropTier: "z-50 dialog",
      dialogTitle: "Delete this session?",
      dialogBody: "Its transcript and Trace files are deleted with it.",
      cancel: "Cancel",
      confirm: "Delete",
      toastTier: "z-[100] toast",
      toast: "Exported Trace #001",
    },
    radius: "Radius",
    shadows: "Shadow levels",
    spacingPage: {
      title: "Settings",
      appearance: "Appearance",
      theme: "Theme",
      themeOptions: ["Light", "Dark", "System"],
      fontSize: "Text size",
      sizeOptions: ["XS", "S", "M", "L", "XL"],
      general: "General",
      language: "Language",
      languageOptions: ["中文", "English"],
      notifications: "Notify when done",
    },
    stack0Note: "stack-0: the narrow bars between a glyph and its label",
    controlHeights: "Control heights, measured",
    iconSizes: "Icon sizes",
    iconRegistry: (icons, files) => `${icons} icons from ${files} files`,
    duplicateNames: "One path, several names",
    durations: "Durations × easings",
    reducedNote: "Reduced motion: every change shows its end state at once.",
    liveSignal: "Live signals",
    loading: "Loading",
    focusRing: "Focus ring",
    inputFocus: "Input focus",
    selection: "Selection",
    scrollbar: "Scrollbar",
    spaceUnit: "Space unit",
    spaceUnitNote: "Every spacing and size utility is a multiple of it: h-8 is eight units.",
    shell: "Shell",
    shellNote:
      "The app window through .ui-shell: the field, the navigation column and the main column, related as each theme decides.",
    presence: "Presence",
    presenceNote:
      "A menu from the top, a dialog from the centre, a toast from the bottom — each on the active theme's enter and exit tokens.",
    reveal: "Reveal",
    revealNote:
      "Streamed text arrives chunk by chunk; each chunk moves once, on the reveal tokens, as it appears.",
    layout: "Layout",
    layoutNote: "The sidebar's width between expanded and rail, on the layout tokens.",
    replay: "Replay",
    replayAll: "Replay all",
    motionSpecimens: {
      menu: "Menu",
      dialog: "Dialog",
      toast: "Toast",
      trigger: "More",
      sidebarRows: ["New chat", "Agents", "Models"],
    },
    hookJobs: {
      "ui-glass": "a transient layer over content",
      "ui-eyebrow": "a group label naming the items below it",
      "ui-display": "the one display title of a page or hero",
      "ui-live": "motion for something running right now",
      "ui-frame": "a ruled box with a head, a body, a foot and panes",
      "ui-underline-nav": "the selected-tab marker of a tab bar",
      "ui-shell": "the app window: a navigation column beside a main column",
      "ui-icon-decor": "an icon its label already says: a theme may tint it or drop it",
      "ui-tree":
        "a list whose rows nest: a file tree, a work group's tool rows, the subagent graph",
      "ui-field": "a labelled control row: a form field or a settings row",
      "ui-activity": "a thinking or tool row at work: running, done or in error",
      "ui-notice":
        "a notice strip or toast, coloured by its tone: info, success, warning, danger or neutral",
      "ui-chart": "a chart: its grid, axes, lines, areas, bars and points",
      "ui-scrim": "the dimmed layer behind a dialog, drawer or sheet",
      "ui-stream": "a reply that is still streaming: each theme decides how new text appears",
    },
    hookSamples: {
      menu: ["Pin", "Rename", "Delete"],
      group: "Workspaces",
      rows: ["claude-code-expert", "docs-sync", "release-notes"],
      copy: "Copy",
      tabs: ["Overview", "Traces", "Files"],
      streaming: "Writing the answer",
      tree: {
        root: "claude-code-expert",
        dir: "src",
        files: ["rag.ts", "embed.ts"],
        last: "README.md",
      },
      field: {
        name: "Name",
        value: "Docs Expert",
        hint: "Shown in the sidebar and in messages.",
        notify: "Notify when done",
        notifyHint: "A system notification when a Task ends.",
      },
    },
  },
  fonts: {
    title: "Fonts",
    pages: { defaults: "Defaults", specimens: "Specimens", licences: "Licences" },
    defaultsTitle: "Default faces",
    defaultsHint:
      "Each theme's default face per role: Latin (reading and interface), CJK and mono. “System” leaves the role to the platform.",
    system: "System",
    current: "Current choice",
    currentHint:
      "The pairing picked in the top bar; “theme default” is the active theme's row above. What actually renders is on the next line.",
    followsTheme: (theme) => `Theme default (${theme})`,
    specimensTitle: "Specimens",
    licencesTitle: "Licences",
    specimens: "Specimens",
    specimensHint:
      "Each theme's families, one en and one zh paragraph at the five text sizes (14 / 15 / 16 / 18 / 20 px).",
    declared: "Declared faces",
    declaredHint:
      "The @font-face rules in the page's stylesheets, merged by family, weight and style; a browser downloads a slice only when text uses it.",
    noFaces: "No faces declared.",
    family: "Family",
    weight: "Weight",
    slicesColumn: "Slices",
    loadStatus: "Loaded",
    licences: "Licence texts",
    noLicences: "No licence texts yet.",
    status: { loaded: "loaded", unloaded: "unused", loading: "loading", error: "failed" },
  },
  library: {
    title: "Component library",
    groups: { components: "Components", foundations: "Foundations" },
    topics: {
      buttons: {
        title: "Buttons",
        description:
          "Five variants, five sizes and the icon button; disabled and loading; links and keyboard hints.",
      },
      inputs: {
        title: "Inputs and forms",
        description:
          "Input, textarea, password, search, checkbox and radio on the field scaffolding: label, hint, info and error.",
      },
      pickers: {
        title: "Pickers",
        description:
          "Select, segmented control, switch and toggle rows, swatches, option menu, dropdown and menu rows.",
      },
      toasts: {
        title: "Toasts",
        description:
          "The notice after an action completes: success, info, attention and error, fired from buttons.",
      },
      notices: {
        title: "Notice strips",
        description:
          "A notice that owns a row: every tone, with and without actions; the three notice variants built on it, and the page to-do.",
      },
      dialogs: {
        title: "Dialogs",
        description:
          "Modal, confirmation, paged dialog, drawer, bottom sheet, lightbox and command palette.",
      },
      tooltips: {
        title: "Tooltips",
        description:
          "Hints on hover and focus: the data-tooltip attribute and the Tooltip component.",
      },
      tabs: { title: "Tabs", description: "The underline tab switcher, with an update badge." },
      badges: {
        title: "Badges and status",
        description:
          "Badges and counts, state dots, run-state icons, session activity marks, the update dot, and the stat tile and chip.",
      },
      empty: {
        title: "Empty states",
        description: "The placeholder for a list or detail with nothing in it, with an action.",
      },
      loading: {
        title: "Loading",
        description: "The spinner, the skeletons and the progress bar.",
      },
      streaming: {
        title: "Streaming",
        description:
          "How an assistant reply reveals as it streams in: Primer shows it at once, Frost fades it in word by word with a soft glow, Console types it out.",
      },
      charts: {
        title: "Charts",
        description:
          "The chart foundation: the primitives every chart draws through, the current theme's chart tokens, and every chart built on them — the donut, the ring gauge, the legend, cost trend and token bars, requests and success rate, the sparkline, the Trace timeline.",
      },
      avatars: {
        title: "Avatars",
        description: "The user and agent avatars at their sizes, and a stack of them.",
      },
      files: {
        title: "Files",
        description:
          "The file tree and the read-only file browser; the Files panel's tree and preview panes with the draggable split between them, the path strip, the file menu, the editor and the drop feedback.",
      },
      content: {
        title: "Content",
        description:
          "Headings and text roles, inline code, Markdown prose, code blocks and surfaces, and the diff viewer.",
      },
      layout: {
        title: "Layout",
        description:
          "The page frame and header, cards and their headers, ruled and collapsible sections, the entity header and the navigation list.",
      },
      data: {
        title: "Data",
        description: "Tables, list rows, label/value pairs and the log view.",
      },
      colour: {
        title: "Colour",
        description: "Surfaces, inks, lines, the accent, the tones, chart series and code colours.",
      },
      type: { title: "Typography", description: "Size, line height and weight per role." },
      shape: { title: "Shape", description: "Radii, the shadow tiers and nesting." },
      density: { title: "Density", description: "The space unit and the control heights." },
      focus: { title: "Focus", description: "Focus ring, input focus, selection and scrollbars." },
      motion: { title: "Motion", description: "Presence, reveal, layout, durations and easing." },
      icons: { title: "Icons", description: "Icon sizes and the Web App's icon registry." },
      hooks: {
        title: "Hooks",
        description: "The structural hooks a theme may redraw, one by one.",
      },
    },
    buttons: {
      variants: "Variants",
      primary: "Save",
      secondary: "Cancel",
      danger: "Delete",
      ghost: "More",
      link: "View details",
      sizes: "Sizes",
      md: "Default size",
      sm: "Small",
      xs: "Extra small",
      leading: "New",
      icon: "Icon button",
      iconHint: "The label is required: it is both the accessible name and the tooltip.",
      add: "Add",
      edit: "Edit",
      states: "States",
      disabled: "Disabled",
      busy: "Saving…",
      links: "Links",
      linksHint:
        "A link in a sentence is always underlined; a standalone one shows the underline on hover. An external link opens in a new tab and carries the external mark.",
      inlineBefore: "See the ",
      inlineLink: "release notes",
      inlineAfter: " for what changed.",
      external: "All releases",
      keys: "Keyboard hints",
      shortcuts: [["Ctrl", "K"], ["Ctrl", "`"], ["Esc"]],
    },
    inputs: {
      basics: "Inputs",
      name: "Name",
      namePlaceholder: "Docs Expert",
      nameHint: "Shown in the sidebar and in messages.",
      email: "Email",
      emailValue: "zheng@example",
      emailError: "The address is incomplete.",
      required: "Required",
      info: "With info",
      infoText: "Takes effect when the next Task starts.",
      sizes: "Sizes",
      base: "Base size",
      small: "Form size",
      textarea: "Textarea",
      textareaPlaceholder: "Write a system prompt…",
      mono: "Monospace",
      monoValue: "temperature: 0.2\nmax_tokens: 4096",
      password: "Password",
      passwordHint: "At least 12 characters.",
      affix: "In-field affixes",
      affixContext: "Context window",
      affixToken: "Token",
      affixPrice: "Output price",
      affixCurrency: "$",
      affixUnit: "/M tok",
      search: "Search boxes",
      searchField: "Search plugins",
      searchIcon: "Search sessions",
      searchPanel: "Filter files",
      searchMenu: "Search skills",
      checkboxes: "Checkboxes",
      checkboxLabel: "Clear the stored key",
      checkboxHint: "Applied when you save.",
      checkboxAll: "All plugins",
      checkboxDisabled: "Locked by the administrator",
      radios: "Radio groups",
      radioLabel: "When a name already exists",
      radioSkip: "Skip it",
      radioSkipHint: "Keep what is there; nothing is lost.",
      radioOverwrite: "Overwrite it",
      radioOverwriteHint: "Replace the files that share a name.",
      radioReplace: "Replace everything",
      radioReplaceHint: "Remove what the import does not contain.",
      radioInline: "On one line",
    },
    pickers: {
      select: "Select",
      selectLabel: "Model",
      options: ["DeepSeek V4.1 Flash", "Claude Sonnet 4.5", "GLM-5.3"],
      segmented: "Segmented",
      segments: ["Light", "Dark", "System"],
      switches: "Switch",
      switchLabel: "Notify when done",
      switchHint: "A system notification when a Task ends.",
      switchOff: "Short tool names",
      toggleRows: "Toggle rows",
      toggleRowLabel: "Show the launcher",
      toggleRowInfo:
        "The round button in the workbench corner that fans out the terminal, files and preview.",
      togglePlainLabel: "Use the proxy for the app's requests",
      togglePlainHint: "Takes effect once saved.",
      toggleCardLabel: "Enable memory",
      swatches: "Swatches",
      optionMenu: "Option menu",
      optionLabel: "Permission",
      choices: [
        {
          value: "r",
          trigger: "r",
          label: "Read only",
          description: "Can only read the workspace.",
        },
        {
          value: "rw",
          trigger: "rw",
          label: "Read and write",
          description: "May change files in the workspace.",
        },
        {
          value: "ask",
          trigger: "ask",
          label: "Ask each time",
          description: "Asks before every write.",
        },
      ],
      dropdown: "Dropdown",
      menu: "More actions",
      menuPin: "Pin",
      menuRename: "Rename",
      menuMove: "Move to…",
      menuDelete: "Delete",
      menuRows: "Menu rows",
      menuRowsHint:
        "Two densities: the account and project menus on the body size, a row's more and context menus on the small size.",
      menuSettings: "Settings",
      menuUpdate: "Check for updates",
      menuVersion: "v0.2.13",
      menuSignOut: "Sign out",
      menuGroupBy: "Group by",
      menuByWorkspace: "By Workspace",
      menuByAgent: "By agent",
      menuSortBy: "Sort by",
      menuRecent: "Recently active",
      menuManual: "Manual order",
    },
    toasts: {
      fire: "Fire a toast",
      hint: "A toast appears at the top of the page and leaves after a few seconds; an error or an advisory stays longer.",
      success: "Success",
      info: "Info",
      attention: "Attention",
      error: "Error",
      successText: "Saved.",
      infoText: "The index is rebuilding in the background.",
      attentionText: "Saved, but 2 fields were truncated.",
      errorText: "Connection failed: api.example is unreachable.",
    },
    notices: {
      plain: "Every tone",
      dotted: "With a leading mark",
      withActions: "With actions",
      texts: {
        info: "Version 0.3.0 is available.",
        success: "Index rebuilt: 214 files.",
        attention: "1 unexpected error.",
        danger: "The model returned 401: invalid key.",
        neutral: "This session is archived.",
      },
      action: "View",
      dismiss: "Dismiss",
      variants: "Three variants",
      variantNames: {
        strip: "Strip: across a panel",
        callout: "Callout: a block of its own",
        inline: "Inline: inside the content",
      },
      retry: "Retry",
      calloutTitle: "The template has no memory placeholder",
      calloutBody: "Insert the placeholder into the prompt template to inject memory.",
      todo: "Page to-do",
      todoText: "3 skills can be updated",
      todoAction: "Update all",
      todoDismiss: "Mark as read",
    },
    dialogs: {
      modal: "Modal",
      openModal: "Open a dialog",
      modalTitle: "Rename session",
      modalBody: "The new name shows in the sidebar and in messages.",
      save: "Save",
      cancel: "Cancel",
      confirm: "Confirmation",
      openConfirm: "Delete session…",
      confirmTitle: "Delete this session?",
      confirmBody: "The transcript and the Trace files go with it; this cannot be undone.",
      confirmLabel: "Delete",
      openSaveConfirm: "Save changes…",
      saveConfirmTitle: "Save these changes?",
      saveConfirmBody: "The agent uses the new settings from its next task.",
      paged: "Paged dialog",
      openPaged: "Open settings",
      pagedTitle: "Settings",
      pagedGroups: { app: "App", you: "Account" },
      pages: { general: "General", appearance: "Appearance", account: "Profile" },
      pageBody: "The current page's settings go here.",
      appearanceInfo: "Theme, accent and density apply to this browser only.",
      drawer: "Drawer",
      openDrawer: "Open a drawer",
      drawerTitle: "Navigation",
      drawerBody: "The sidebar at phone width slides in from the edge.",
      sheet: "Bottom sheet",
      openSheet: "Open a sheet",
      sheetTitle: "Files",
      sheetBody: "Drag up for the full screen, down to close.",
      lightbox: "Lightbox",
      lightboxHint: "Click the thumbnail to zoom in; Esc or a click outside the image closes it.",
      lightboxAlt: "The Penguin logo",
      palette: "Command palette",
      paletteAside: "Type to filter; each action opens another dialog on this board.",
      openPalette: "Open the command palette",
      palettePlaceholder: "Type to filter commands…",
      paletteEmpty: "No matching commands",
      paletteHint: "↑↓ to select · Enter to run · Esc to close",
    },
    tooltips: {
      attribute: "The data-tooltip attribute",
      attributeHint:
        "Any element takes the attribute; an icon-only button carries an aria-label too.",
      component: "The Tooltip component",
      componentHint: "For a trigger that needs the wrapper: beside it, or below it.",
      truncated: "Truncated text",
      truncatedHint: "A command or title the row cannot fit goes whole into the hint.",
      edit: "Edit",
      copy: "Copy",
      settings: "Settings",
      besideTip: "Opens to the right of its trigger",
      belowTip: "Opens under its trigger",
      command:
        "pnpm --filter @lmliheng/penguin-web exec vitest run test/session-activity.test.ts --reporter verbose",
    },
    tabs: {
      basic: "Tab switcher",
      badged: "With an update badge",
      items: ["Overview", "Trace", "Files", "Settings"],
      badgeText: "3 skills can be updated",
      body: (tab) => `The “${tab}” tab's content.`,
    },
    badges: {
      badges: "Badges",
      tones: {
        neutral: "default",
        success: "running",
        attention: "aborted",
        danger: "failed",
        done: "done",
        info: "free",
      },
      variants: { soft: "Soft", outline: "Outline", solid: "Solid" },
      count: "Count",
      dots: "State dots",
      dotsHint: "Six tones; only what is live pulses",
      live: "Live",
      status: "Run state",
      states: {
        running: "Running",
        waiting: "Waiting for approval",
        done: "Done",
        failed: "Failed",
        stopped: "Stopped",
      },
      activity: "Session activity",
      activities: { running: "Running", compacting: "Compacting", completedUnread: "Unread reply" },
      marks: "Other marks",
      background: "Background tasks",
      schedule: "Scheduled",
      dot: "Update dot",
      dotAnchor: "Plugins",
      pill: "Update pill",
      pillText: "3 updates",
      statTile: "Stat tiles",
      spend: "Spend this month",
      spendDetail: "Organization budget $40",
      alerts: "Alerts",
      alertsDetail: "1 over budget, 1 paused",
      statChip: "Stat chips",
      input: "Input",
      output: "Output",
      elapsed: "Elapsed",
    },
    empty: {
      page: "Page empty state",
      title: "No sessions yet",
      description: "Sessions appear here once you send a first message.",
      action: "New chat",
      settings: "Settings empty state",
      settingsText: "No MCP servers added yet.",
    },
    loading: {
      spinner: "Spinner",
      sizes: "Three sizes",
      skeleton: "Skeletons",
      list: "List",
      card: "Card",
      progress: "Progress bar",
      progressHint: "Three heights; still while indeterminate",
      progressLabel: "Download progress",
      progressOver: "Over the limit",
      progressIndeterminate: "Indeterminate",
    },
    streaming: {
      reply: "Assistant reply",
      receiving: "Receiving…",
      received: "All received",
      modes: {
        instant: "shows text the moment it arrives, with no motion",
        fade: "fades in word by word, the last lines rising out of a softly glowing accent veil",
        typewriter: "types out character by character behind a solid block caret",
      },
      unset: "treated as instant",
      rate: (perSecond) => `about ${Math.round(perSecond)} characters a second`,
      reduced: "reduced motion is on, so the reply shows as it arrives",
    },
    charts: {
      parts: {
        primitives: "Primitives",
        primitivesHint:
          "Every chart draws its marks through these alone: they read the theme's chart tokens and write data-part, the one place a token becomes SVG or HTML.",
        tokens: "The current theme's chart tokens",
        tokensHint:
          "Read from this frame root's computed style; read again after a theme, mode or accent change.",
        charts: "Charts built on them",
        chartsHint: "Every chart kind in the app, on demo data.",
      },
      primitives: {
        bar: "ChartBar",
        barHint: "Its width from bar-fill; top radius, outline and fill opacity each from a token.",
        line: "ChartLine",
        lineHint: "One set of points drawn once per curve; the stroke width from a token.",
        curves: { linear: "linear", smooth: "smooth", step: "step" },
        area: "ChartArea",
        areaHint: "The fill under a line, its opacity from a token.",
        point: "ChartPoint",
        pointHint: "Radius from a token; the theme decides round or square.",
        arc: "ChartArc",
        arcHint:
          "One arc of a ring: the track is a grid part, each segment a Token kind or a slot.",
        grid: "ChartGrid and ChartAxis",
        gridHint: "Grid and axis inks from tokens; the theme decides solid or dashed.",
        timeline: "TimelineBar",
        timelineHint: "The Trace timeline's HTML bar, each of the five kinds on its slot.",
        kinds: {
          thinking: "thinking",
          text: "reply",
          tool_call: "tool call",
          approval: "approval wait",
          tool: "tool run",
        },
      },
      palette: "Palette",
      geometry: "Geometry",
      tokenMeaning: {
        "--ui-chart-1": "slot 1 · violet",
        "--ui-chart-2": "slot 2 · amber",
        "--ui-chart-3": "slot 3 · sky",
        "--ui-chart-4": "slot 4 · rose",
        "--ui-chart-5": "slot 5 · emerald",
        "--ui-chart-6": "slot 6 · fuchsia",
        "--ui-chart-7": "slot 7 · spare",
        "--ui-chart-8": "slot 8 · spare",
        "--ui-chart-ref": "reference line",
        "--ui-chart-cache-read": "cache read",
        "--ui-chart-cache-write": "cache write",
        "--ui-chart-output": "output",
        "--ui-chart-grid": "grid",
        "--ui-chart-axis": "axis",
        "--ui-chart-bar-fill": "share of its band a bar fills (0–1)",
        "--ui-chart-bar-radius": "bar top radius",
        "--ui-chart-bar-stroke": "bar outline width",
        "--ui-chart-bar-stroke-color": "bar outline colour (series = the series colour)",
        "--ui-chart-bar-opacity": "bar fill opacity (0–1)",
        "--ui-chart-line-width": "line width",
        "--ui-chart-point-radius": "data point radius",
        "--ui-chart-curve": "curve (linear / smooth / step)",
        "--ui-chart-area-opacity": "area fill opacity (0–1)",
      },
      donut: "Token donut",
      donutHint:
        "Cache reads, cache writes and output; the ring's remainder warns as usage nears the limit.",
      donutLabels: {
        usage: "Context usage",
        cacheRead: "Cache read",
        cacheWrite: "Cache write",
        output: "Output",
      },
      ring: "Ring gauge",
      ringHint:
        "One arc against a budget in the budget's tone (under, near, over); without a budget the track stands alone; several arcs split a whole into shares. The composer's context ring (ContextRing) stays in the muted ink to 80 %, turns to attention past it and to danger past 95 %.",
      ringSpend: (percent) => `Spend at ${percent}% of the budget`,
      ringNoBudget: "No budget set",
      ringShares: "Shares of a whole",
      ringContext: "Context ring",
      ringContextAt: (percent) => `Context ${percent}% full`,
      legend: "Legend",
      legendHint:
        "A row under a chart: pointing at one item fades the others, and an item that explains a line's shape stays out of it. A list legend prints each item's figures after its label and pins a row on click.",
      legendHitRate: "Cache hit rate",
      legendParts: ["System prompt", "Tool definitions", "Messages", "Tool results"],
      trend: "Cost trend",
      trendHint: "Fourteen days of cost as a line; hover a day.",
      tokens: "Token usage",
      tokensHint:
        "Daily tokens stacked by kind, with the cache-hit-rate curve over them; hover a legend entry to highlight one.",
      requests: "Requests and success rate",
      requestsHint: "Daily requests stacked by agent, each with its success-rate line.",
      agents: ["docs-expert", "release-notes"],
      activity: "Activity sparkline",
      activityHint:
        "The agent card's fourteen-day session count curve; relative ups and downs only.",
      sparkline: "Score sparkline",
      sparklineHint:
        "One benchmark's scores over its runs, the newest marked; a single score is a lone point.",
      timeline: "Trace timeline",
      timelineHint:
        "One Task's model segments and tool calls: thinking, reply, tool-call generation, approval wait and execution, each in its lane.",
    },
    avatars: {
      user: "User avatar",
      agent: "Agent avatar",
      stack: "Avatar stack",
      stackShown: (shown, total) => `${shown} of ${total} shown`,
      userNames: ["admin", "Demo admin"],
      agents: [
        { id: "docs-expert", name: "Docs Expert" },
        { id: "release-notes", name: "Release Notes" },
        { id: "qa", name: "QA" },
      ],
    },
    files: {
      tree: "File tree",
      treeLabel: "Workspace",
      browser: "File browser",
      header: "docs-expert",
      emptyPreview: "Pick a file on the left to preview it.",
      emptyDir: "Empty directory",
      root: ".",
      readme:
        "# Docs Expert\n\nBuilds a BM25 index over `corpus/` and answers questions about the Claude Code docs.\n\n- `src/rag.ts` — retrieval\n- `test/` — cases",
      truncated: "File too large; preview truncated, download for the full file",
      unsupported: "Preview not supported for this type; download instead",
      download: "Download",
      panel: "Files panel",
      panelHint:
        "The tree beside the preview: the draggable split, the path strip and the actions over the preview",
      search: "Search files",
      treeWidth: "Resize the file tree",
      selectFile: "Select a file to preview",
      wrap: "Wrap lines",
      crumbs: "Path strip",
      crumbsHint:
        "When the path does not fit, its leading parts fold into one “…”; the file name gives way last",
      menu: "File menu",
      menuFile: "File",
      menuFolder: "Folder",
      copyPath: "Copy relative path",
      addToChat: "Add to conversation",
      addSelection: "Add selection to conversation",
      uploadHere: "Upload here",
      rename: "Rename or move",
      delete: "Delete",
      newTextFile: "New text file",
      newFolder: "New folder",
      editor: "Editor",
      editorLabel: (name: string) => `Editing ${name}`,
      drop: "Drop feedback",
      dropAttach: "Drop files to attach",
      dropAttachHint: "Images and files are added to the message draft",
      dropUpload: (dir: string) => `Drop to upload into ${dir}`,
    },
    content: {
      headings: "Headings",
      headingsHint: "Each level takes the theme's rung; the display title is for a page's h1 only.",
      display: "Page display title",
      heading: (level: number) => `Heading ${level}`,
      text: "Text roles",
      samples: {
        body: "Body: the size of messages, notes and settings.",
        small: "Small: secondary information and metadata.",
        caption: "Caption: a note under a chart or a control.",
        eyebrow: "Group label",
        mono: "sess_7f3a · ~/work/penguin",
        label: "Field label",
      },
      inline: { before: "Run ", code: "pnpm install", after: " to install the dependencies." },
      prose: "Markdown prose",
      proseSample:
        "## Release checks\n\nConfirm **three things** before you release, then run `pnpm -r build`. See the [release notes](https://penguin.ooo).\n\n- Type checks pass\n- Every test passes\n- The changelog is written\n\n> When a data root is taken, use another one — never end someone else's process.\n\n| Check | Command |\n| --- | --- |\n| Types | `pnpm typecheck` |\n| Tests | `pnpm test` |\n\n```bash\npnpm -r build && pnpm test\n```\n\nThe cache hit rate is \\(r = h / (h + m)\\).",
      compact: "Compact: a channel message",
      compactSample: "Merged **#897** — `feat/ui-w2` can go.",
      code: "Code",
      surface: "Code surface: line numbers, no frame",
      diff: "Diff",
      unified: "Unified",
      split: "Side by side",
      patch: "From a patch",
      diffLabel: "Changes to src/config.ts",
      patchLabel: "Changes to src/limits.ts",
    },
    layout: {
      page: "Page and header",
      pageHint:
        "A page header has one display title and no eyebrow; the way back sits above the title, the actions at the end of its row.",
      pageTitle: "Agents",
      pageInfo: "Each agent has its own prompt, tools, skills and memory.",
      pageDescription: "4 agents in this project.",
      pageBody: "The page's content starts here.",
      back: "Back to the list",
      search: "Search agents",
      create: "New",
      cards: "Cards",
      padded: "Padded: a title row above the content",
      cardTitle: "Spend this month",
      cardInfo: "What every agent spent on models this month.",
      cardAction: "Export",
      cardValue: "$128.45",
      cardBody: "12% less than last month.",
      flush: "Flush: rows run edge to edge under a ruled strip",
      flushTitle: "Recent sessions",
      flushDescription: "By their last message.",
      flushRows: [
        "Draft this week's release notes",
        "Find the skipped scheduled run",
        "Add three cases to the eval set",
      ],
      ruled: "Ruled section",
      ruledTitle: "Inbox",
      ruledInfo: "Tickets waiting on you: to review, or sent back.",
      ruledAction: "Mark all read",
      ruledBody: "Three tickets wait for your review.",
      collapsible: "Collapsible section",
      collapsibleHint:
        "The fold is layout motion: the body's grid row goes between 1fr and 0fr, and the theme decides how it moves.",
      providerName: "OpenAI",
      modelCount: (n: number) => (n === 1 ? "1 model" : `${n} models`),
      addModel: "Add a model",
      foldedTitle: "Custom",
      foldedBody: "This group has no models yet.",
      entity: "Entity header",
      entityName: "Code reviewer",
      entityDescription:
        "Reads every PR's diff and raises only the problems that would cause a bug.",
      copyId: "Copy id",
      entityAction: "Open a session",
      entityTags: ["review", "read-only"],
      nav: "Navigation list",
      navHint:
        "The current row takes the solid fill and is the current page; a glyph is decoration beside a label that already says it. A dialog's rail scrolls sideways on a phone.",
      navLabel: "Agent settings",
      navRail: "A rail: glyph, label and a trailing count; the last row has nowhere to go yet",
      navDense: "Dense, inside a panel",
      navRows: {
        overview: "Overview",
        models: "Models",
        schedules: "Schedules",
        vault: "Vault",
        billing: "Billing",
      },
    },
    data: {
      table: "Table",
      tableHint:
        "One header style: the small rung, medium weight, muted ink and a rule; a table on its own is framed, its header on the muted surface.",
      caption: "Schedules",
      columns: {
        name: "Name",
        status: "Status",
        period: "Period",
        cost: "Cost",
        employee: "Employee",
      },
      enabled: "Enabled",
      paused: "Paused",
      pause: "Pause",
      enable: "Enable",
      bare: "A compact table inside a card",
      spendTitle: "Spend by employee",
      employees: ["Researcher", "Writer", "Editor"],
      rows: "List rows",
      rowsHint:
        "A row that opens what it names makes its mark and text one button; its actions stay outside it.",
      skillDescriptions: [
        "Reads PDFs and fills in their forms.",
        "Builds web pages to a design system.",
        "Distils reusable lessons from sessions.",
      ],
      skillMeta: "2 days ago",
      exportSkill: (name: string) => `Export ${name}`,
      clickable: "Rows that open what they name",
      cases: [
        "Form validation on the sign-in page",
        "First commit in an empty repository",
        "Truncating a very long file name",
      ],
      keyValue: "Label and value",
      labels: {
        version: "Version",
        started: "Started",
        root: "Data root",
        machineId: "Machine id",
      },
      log: "Log",
      logHint: "A job still running: its latest line in the body ink.",
      logLabel: "Update output",
    },
  },
};
